// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sql

import (
	"database/sql"

	"github.com/google/uuid"
)

type Barn struct {
	ID            uuid.UUID
	FarmID        uuid.UUID
	Feed          int64
	HasAutoFeeder bool
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type Chicken struct {
	ID             uuid.UUID
	BarnID         uuid.UUID
	DateOfBirth    int64
	RestingUntil   int64
	NormalEggsLaid int64
	GoldEggsLaid   int64
	GoldEggChance  int64
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type Farm struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
