// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: chicken_farmer/v1/farm.proto

package grpc

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Farm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Day        uint32  `protobuf:"varint,2,opt,name=day,proto3" json:"day,omitempty"`
	GoldenEggs uint32  `protobuf:"varint,3,opt,name=golden_eggs,json=goldenEggs,proto3" json:"golden_eggs,omitempty"`
	Barns      []*Barn `protobuf:"bytes,4,rep,name=barns,proto3" json:"barns,omitempty"`
}

func (x *Farm) Reset() {
	*x = Farm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chicken_farmer_v1_farm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Farm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Farm) ProtoMessage() {}

func (x *Farm) ProtoReflect() protoreflect.Message {
	mi := &file_chicken_farmer_v1_farm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Farm.ProtoReflect.Descriptor instead.
func (*Farm) Descriptor() ([]byte, []int) {
	return file_chicken_farmer_v1_farm_proto_rawDescGZIP(), []int{0}
}

func (x *Farm) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Farm) GetDay() uint32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *Farm) GetGoldenEggs() uint32 {
	if x != nil {
		return x.GoldenEggs
	}
	return 0
}

func (x *Farm) GetBarns() []*Barn {
	if x != nil {
		return x.Barns
	}
	return nil
}

type Barn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Feed          uint32     `protobuf:"varint,2,opt,name=feed,proto3" json:"feed,omitempty"`
	HasAutoFeeder bool       `protobuf:"varint,3,opt,name=has_auto_feeder,json=hasAutoFeeder,proto3" json:"has_auto_feeder,omitempty"`
	Chickens      []*Chicken `protobuf:"bytes,4,rep,name=chickens,proto3" json:"chickens,omitempty"`
}

func (x *Barn) Reset() {
	*x = Barn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chicken_farmer_v1_farm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Barn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Barn) ProtoMessage() {}

func (x *Barn) ProtoReflect() protoreflect.Message {
	mi := &file_chicken_farmer_v1_farm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Barn.ProtoReflect.Descriptor instead.
func (*Barn) Descriptor() ([]byte, []int) {
	return file_chicken_farmer_v1_farm_proto_rawDescGZIP(), []int{1}
}

func (x *Barn) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Barn) GetFeed() uint32 {
	if x != nil {
		return x.Feed
	}
	return 0
}

func (x *Barn) GetHasAutoFeeder() bool {
	if x != nil {
		return x.HasAutoFeeder
	}
	return false
}

func (x *Barn) GetChickens() []*Chicken {
	if x != nil {
		return x.Chickens
	}
	return nil
}

type Chicken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DateOfBirth    uint32 `protobuf:"varint,2,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	RestingUntil   uint32 `protobuf:"varint,5,opt,name=resting_until,json=restingUntil,proto3" json:"resting_until,omitempty"`
	NormalEggsLaid uint32 `protobuf:"varint,3,opt,name=normal_eggs_laid,json=normalEggsLaid,proto3" json:"normal_eggs_laid,omitempty"`
	GoldEggsLaid   uint32 `protobuf:"varint,4,opt,name=gold_eggs_laid,json=goldEggsLaid,proto3" json:"gold_eggs_laid,omitempty"`
}

func (x *Chicken) Reset() {
	*x = Chicken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chicken_farmer_v1_farm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chicken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chicken) ProtoMessage() {}

func (x *Chicken) ProtoReflect() protoreflect.Message {
	mi := &file_chicken_farmer_v1_farm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chicken.ProtoReflect.Descriptor instead.
func (*Chicken) Descriptor() ([]byte, []int) {
	return file_chicken_farmer_v1_farm_proto_rawDescGZIP(), []int{2}
}

func (x *Chicken) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chicken) GetDateOfBirth() uint32 {
	if x != nil {
		return x.DateOfBirth
	}
	return 0
}

func (x *Chicken) GetRestingUntil() uint32 {
	if x != nil {
		return x.RestingUntil
	}
	return 0
}

func (x *Chicken) GetNormalEggsLaid() uint32 {
	if x != nil {
		return x.NormalEggsLaid
	}
	return 0
}

func (x *Chicken) GetGoldEggsLaid() uint32 {
	if x != nil {
		return x.GoldEggsLaid
	}
	return 0
}

type NewFarmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerId string `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *NewFarmRequest) Reset() {
	*x = NewFarmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chicken_farmer_v1_farm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewFarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewFarmRequest) ProtoMessage() {}

func (x *NewFarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chicken_farmer_v1_farm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewFarmRequest.ProtoReflect.Descriptor instead.
func (*NewFarmRequest) Descriptor() ([]byte, []int) {
	return file_chicken_farmer_v1_farm_proto_rawDescGZIP(), []int{3}
}

func (x *NewFarmRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *NewFarmRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NewFarmResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FarmId string `protobuf:"bytes,1,opt,name=farm_id,json=farmId,proto3" json:"farm_id,omitempty"`
}

func (x *NewFarmResponse) Reset() {
	*x = NewFarmResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chicken_farmer_v1_farm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewFarmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewFarmResponse) ProtoMessage() {}

func (x *NewFarmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chicken_farmer_v1_farm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewFarmResponse.ProtoReflect.Descriptor instead.
func (*NewFarmResponse) Descriptor() ([]byte, []int) {
	return file_chicken_farmer_v1_farm_proto_rawDescGZIP(), []int{4}
}

func (x *NewFarmResponse) GetFarmId() string {
	if x != nil {
		return x.FarmId
	}
	return ""
}

type DeleteFarmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FarmId string `protobuf:"bytes,1,opt,name=farm_id,json=farmId,proto3" json:"farm_id,omitempty"`
}

func (x *DeleteFarmRequest) Reset() {
	*x = DeleteFarmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chicken_farmer_v1_farm_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFarmRequest) ProtoMessage() {}

func (x *DeleteFarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chicken_farmer_v1_farm_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFarmRequest.ProtoReflect.Descriptor instead.
func (*DeleteFarmRequest) Descriptor() ([]byte, []int) {
	return file_chicken_farmer_v1_farm_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteFarmRequest) GetFarmId() string {
	if x != nil {
		return x.FarmId
	}
	return ""
}

type DeleteFarmResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteFarmResponse) Reset() {
	*x = DeleteFarmResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chicken_farmer_v1_farm_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFarmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFarmResponse) ProtoMessage() {}

func (x *DeleteFarmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chicken_farmer_v1_farm_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFarmResponse.ProtoReflect.Descriptor instead.
func (*DeleteFarmResponse) Descriptor() ([]byte, []int) {
	return file_chicken_farmer_v1_farm_proto_rawDescGZIP(), []int{6}
}

type FarmDetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FarmDetailsRequest) Reset() {
	*x = FarmDetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chicken_farmer_v1_farm_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FarmDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FarmDetailsRequest) ProtoMessage() {}

func (x *FarmDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chicken_farmer_v1_farm_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FarmDetailsRequest.ProtoReflect.Descriptor instead.
func (*FarmDetailsRequest) Descriptor() ([]byte, []int) {
	return file_chicken_farmer_v1_farm_proto_rawDescGZIP(), []int{7}
}

type FarmDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Farm *Farm `protobuf:"bytes,1,opt,name=farm,proto3" json:"farm,omitempty"`
}

func (x *FarmDetailsResponse) Reset() {
	*x = FarmDetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chicken_farmer_v1_farm_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FarmDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FarmDetailsResponse) ProtoMessage() {}

func (x *FarmDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chicken_farmer_v1_farm_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FarmDetailsResponse.ProtoReflect.Descriptor instead.
func (*FarmDetailsResponse) Descriptor() ([]byte, []int) {
	return file_chicken_farmer_v1_farm_proto_rawDescGZIP(), []int{8}
}

func (x *FarmDetailsResponse) GetFarm() *Farm {
	if x != nil {
		return x.Farm
	}
	return nil
}

type BuyBarnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BuyBarnRequest) Reset() {
	*x = BuyBarnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chicken_farmer_v1_farm_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyBarnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyBarnRequest) ProtoMessage() {}

func (x *BuyBarnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chicken_farmer_v1_farm_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyBarnRequest.ProtoReflect.Descriptor instead.
func (*BuyBarnRequest) Descriptor() ([]byte, []int) {
	return file_chicken_farmer_v1_farm_proto_rawDescGZIP(), []int{9}
}

type BuyBarnResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BuyBarnResponse) Reset() {
	*x = BuyBarnResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chicken_farmer_v1_farm_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyBarnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyBarnResponse) ProtoMessage() {}

func (x *BuyBarnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chicken_farmer_v1_farm_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyBarnResponse.ProtoReflect.Descriptor instead.
func (*BuyBarnResponse) Descriptor() ([]byte, []int) {
	return file_chicken_farmer_v1_farm_proto_rawDescGZIP(), []int{10}
}

type BuyFeedBagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BarnId string `protobuf:"bytes,1,opt,name=barn_id,json=barnId,proto3" json:"barn_id,omitempty"`
	Amount uint32 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *BuyFeedBagRequest) Reset() {
	*x = BuyFeedBagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chicken_farmer_v1_farm_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyFeedBagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyFeedBagRequest) ProtoMessage() {}

func (x *BuyFeedBagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chicken_farmer_v1_farm_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyFeedBagRequest.ProtoReflect.Descriptor instead.
func (*BuyFeedBagRequest) Descriptor() ([]byte, []int) {
	return file_chicken_farmer_v1_farm_proto_rawDescGZIP(), []int{11}
}

func (x *BuyFeedBagRequest) GetBarnId() string {
	if x != nil {
		return x.BarnId
	}
	return ""
}

func (x *BuyFeedBagRequest) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type BuyFeedBagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BuyFeedBagResponse) Reset() {
	*x = BuyFeedBagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chicken_farmer_v1_farm_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyFeedBagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyFeedBagResponse) ProtoMessage() {}

func (x *BuyFeedBagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chicken_farmer_v1_farm_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyFeedBagResponse.ProtoReflect.Descriptor instead.
func (*BuyFeedBagResponse) Descriptor() ([]byte, []int) {
	return file_chicken_farmer_v1_farm_proto_rawDescGZIP(), []int{12}
}

type BuyChickenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BarnId string `protobuf:"bytes,1,opt,name=barn_id,json=barnId,proto3" json:"barn_id,omitempty"`
}

func (x *BuyChickenRequest) Reset() {
	*x = BuyChickenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chicken_farmer_v1_farm_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyChickenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyChickenRequest) ProtoMessage() {}

func (x *BuyChickenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chicken_farmer_v1_farm_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyChickenRequest.ProtoReflect.Descriptor instead.
func (*BuyChickenRequest) Descriptor() ([]byte, []int) {
	return file_chicken_farmer_v1_farm_proto_rawDescGZIP(), []int{13}
}

func (x *BuyChickenRequest) GetBarnId() string {
	if x != nil {
		return x.BarnId
	}
	return ""
}

type BuyChickenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BuyChickenResponse) Reset() {
	*x = BuyChickenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chicken_farmer_v1_farm_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyChickenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyChickenResponse) ProtoMessage() {}

func (x *BuyChickenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chicken_farmer_v1_farm_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyChickenResponse.ProtoReflect.Descriptor instead.
func (*BuyChickenResponse) Descriptor() ([]byte, []int) {
	return file_chicken_farmer_v1_farm_proto_rawDescGZIP(), []int{14}
}

func (x *BuyChickenResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SellChickenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChickenId string `protobuf:"bytes,1,opt,name=chicken_id,json=chickenId,proto3" json:"chicken_id,omitempty"`
}

func (x *SellChickenRequest) Reset() {
	*x = SellChickenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chicken_farmer_v1_farm_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SellChickenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellChickenRequest) ProtoMessage() {}

func (x *SellChickenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chicken_farmer_v1_farm_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellChickenRequest.ProtoReflect.Descriptor instead.
func (*SellChickenRequest) Descriptor() ([]byte, []int) {
	return file_chicken_farmer_v1_farm_proto_rawDescGZIP(), []int{15}
}

func (x *SellChickenRequest) GetChickenId() string {
	if x != nil {
		return x.ChickenId
	}
	return ""
}

type SellChickenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SellChickenResponse) Reset() {
	*x = SellChickenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chicken_farmer_v1_farm_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SellChickenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellChickenResponse) ProtoMessage() {}

func (x *SellChickenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chicken_farmer_v1_farm_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellChickenResponse.ProtoReflect.Descriptor instead.
func (*SellChickenResponse) Descriptor() ([]byte, []int) {
	return file_chicken_farmer_v1_farm_proto_rawDescGZIP(), []int{16}
}

type FeedChickenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChickenId string `protobuf:"bytes,1,opt,name=chicken_id,json=chickenId,proto3" json:"chicken_id,omitempty"`
}

func (x *FeedChickenRequest) Reset() {
	*x = FeedChickenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chicken_farmer_v1_farm_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedChickenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedChickenRequest) ProtoMessage() {}

func (x *FeedChickenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chicken_farmer_v1_farm_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedChickenRequest.ProtoReflect.Descriptor instead.
func (*FeedChickenRequest) Descriptor() ([]byte, []int) {
	return file_chicken_farmer_v1_farm_proto_rawDescGZIP(), []int{17}
}

func (x *FeedChickenRequest) GetChickenId() string {
	if x != nil {
		return x.ChickenId
	}
	return ""
}

type FeedChickenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FeedChickenResponse) Reset() {
	*x = FeedChickenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chicken_farmer_v1_farm_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedChickenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedChickenResponse) ProtoMessage() {}

func (x *FeedChickenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chicken_farmer_v1_farm_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedChickenResponse.ProtoReflect.Descriptor instead.
func (*FeedChickenResponse) Descriptor() ([]byte, []int) {
	return file_chicken_farmer_v1_farm_proto_rawDescGZIP(), []int{18}
}

type FeedChickensOfBarnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BarnId string `protobuf:"bytes,1,opt,name=barn_id,json=barnId,proto3" json:"barn_id,omitempty"`
}

func (x *FeedChickensOfBarnRequest) Reset() {
	*x = FeedChickensOfBarnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chicken_farmer_v1_farm_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedChickensOfBarnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedChickensOfBarnRequest) ProtoMessage() {}

func (x *FeedChickensOfBarnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chicken_farmer_v1_farm_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedChickensOfBarnRequest.ProtoReflect.Descriptor instead.
func (*FeedChickensOfBarnRequest) Descriptor() ([]byte, []int) {
	return file_chicken_farmer_v1_farm_proto_rawDescGZIP(), []int{19}
}

func (x *FeedChickensOfBarnRequest) GetBarnId() string {
	if x != nil {
		return x.BarnId
	}
	return ""
}

type FeedChickensOfBarnResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FeedChickensOfBarnResponse) Reset() {
	*x = FeedChickensOfBarnResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chicken_farmer_v1_farm_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedChickensOfBarnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedChickensOfBarnResponse) ProtoMessage() {}

func (x *FeedChickensOfBarnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chicken_farmer_v1_farm_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedChickensOfBarnResponse.ProtoReflect.Descriptor instead.
func (*FeedChickensOfBarnResponse) Descriptor() ([]byte, []int) {
	return file_chicken_farmer_v1_farm_proto_rawDescGZIP(), []int{20}
}

var File_chicken_farmer_v1_farm_proto protoreflect.FileDescriptor

var file_chicken_farmer_v1_farm_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x63, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x5f, 0x66, 0x61, 0x72, 0x6d, 0x65, 0x72,
	0x2f, 0x76, 0x31, 0x2f, 0x66, 0x61, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11,
	0x63, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x5f, 0x66, 0x61, 0x72, 0x6d, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x6f, 0x70, 0x65, 0x6e,
	0x61, 0x70, 0x69, 0x76, 0x32, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xac, 0x01, 0x0a, 0x04, 0x46, 0x61, 0x72, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x64, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x1f,
	0x0a, 0x0b, 0x67, 0x6f, 0x6c, 0x64, 0x65, 0x6e, 0x5f, 0x65, 0x67, 0x67, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0a, 0x67, 0x6f, 0x6c, 0x64, 0x65, 0x6e, 0x45, 0x67, 0x67, 0x73, 0x12,
	0x2d, 0x0a, 0x05, 0x62, 0x61, 0x72, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x63, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x5f, 0x66, 0x61, 0x72, 0x6d, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x42, 0x61, 0x72, 0x6e, 0x52, 0x05, 0x62, 0x61, 0x72, 0x6e, 0x73, 0x3a, 0x2e,
	0x92, 0x41, 0x2b, 0x0a, 0x29, 0x2a, 0x04, 0x46, 0x61, 0x72, 0x6d, 0xd2, 0x01, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0xd2, 0x01, 0x0b, 0x67, 0x6f, 0x6c, 0x64, 0x65, 0x6e, 0x5f, 0x65, 0x67, 0x67, 0x73,
	0xd2, 0x01, 0x03, 0x64, 0x61, 0x79, 0xd2, 0x01, 0x05, 0x62, 0x61, 0x72, 0x6e, 0x73, 0x22, 0xc0,
	0x01, 0x0a, 0x04, 0x42, 0x61, 0x72, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x65, 0x65, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x66, 0x65, 0x65, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x68,
	0x61, 0x73, 0x5f, 0x61, 0x75, 0x74, 0x6f, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x68, 0x61, 0x73, 0x41, 0x75, 0x74, 0x6f, 0x46, 0x65, 0x65,
	0x64, 0x65, 0x72, 0x12, 0x36, 0x0a, 0x08, 0x63, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x5f,
	0x66, 0x61, 0x72, 0x6d, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x69, 0x63, 0x6b, 0x65,
	0x6e, 0x52, 0x08, 0x63, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x73, 0x3a, 0x34, 0x92, 0x41, 0x31,
	0x0a, 0x2f, 0x2a, 0x04, 0x42, 0x61, 0x72, 0x6e, 0xd2, 0x01, 0x02, 0x69, 0x64, 0xd2, 0x01, 0x04,
	0x66, 0x65, 0x65, 0x64, 0xd2, 0x01, 0x0f, 0x68, 0x61, 0x73, 0x5f, 0x61, 0x75, 0x74, 0x6f, 0x5f,
	0x66, 0x65, 0x65, 0x64, 0x65, 0x72, 0xd2, 0x01, 0x08, 0x63, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e,
	0x73, 0x22, 0x8b, 0x02, 0x0a, 0x07, 0x43, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a,
	0x0d, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x6f, 0x66, 0x5f, 0x62, 0x69, 0x72, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x42, 0x69, 0x72, 0x74,
	0x68, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x75, 0x6e, 0x74,
	0x69, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x74, 0x69, 0x6e,
	0x67, 0x55, 0x6e, 0x74, 0x69, 0x6c, 0x12, 0x28, 0x0a, 0x10, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c,
	0x5f, 0x65, 0x67, 0x67, 0x73, 0x5f, 0x6c, 0x61, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0e, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x45, 0x67, 0x67, 0x73, 0x4c, 0x61, 0x69, 0x64,
	0x12, 0x24, 0x0a, 0x0e, 0x67, 0x6f, 0x6c, 0x64, 0x5f, 0x65, 0x67, 0x67, 0x73, 0x5f, 0x6c, 0x61,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x67, 0x6f, 0x6c, 0x64, 0x45, 0x67,
	0x67, 0x73, 0x4c, 0x61, 0x69, 0x64, 0x3a, 0x57, 0x92, 0x41, 0x54, 0x0a, 0x52, 0x2a, 0x07, 0x43,
	0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0xd2, 0x01, 0x02, 0x69, 0x64, 0xd2, 0x01, 0x0d, 0x64, 0x61,
	0x74, 0x65, 0x5f, 0x6f, 0x66, 0x5f, 0x62, 0x69, 0x72, 0x74, 0x68, 0xd2, 0x01, 0x0d, 0x72, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x75, 0x6e, 0x74, 0x69, 0x6c, 0xd2, 0x01, 0x10, 0x6e, 0x6f,
	0x72, 0x6d, 0x61, 0x6c, 0x5f, 0x65, 0x67, 0x67, 0x73, 0x5f, 0x6c, 0x61, 0x69, 0x64, 0xd2, 0x01,
	0x0e, 0x67, 0x6f, 0x6c, 0x64, 0x5f, 0x65, 0x67, 0x67, 0x73, 0x5f, 0x6c, 0x61, 0x69, 0x64, 0x22,
	0x58, 0x0a, 0x0e, 0x4e, 0x65, 0x77, 0x46, 0x61, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x3a, 0x17, 0x92, 0x41, 0x14, 0x0a, 0x12, 0xd2, 0x01, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0xd2, 0x01, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2a, 0x0a, 0x0f, 0x4e, 0x65, 0x77,
	0x46, 0x61, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07,
	0x66, 0x61, 0x72, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66,
	0x61, 0x72, 0x6d, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46,
	0x61, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x61,
	0x72, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x61, 0x72,
	0x6d, 0x49, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x61, 0x72,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x46, 0x61, 0x72,
	0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x50, 0x0a, 0x13, 0x46, 0x61, 0x72, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x66, 0x61, 0x72, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x5f, 0x66,
	0x61, 0x72, 0x6d, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x61, 0x72, 0x6d, 0x52, 0x04, 0x66,
	0x61, 0x72, 0x6d, 0x3a, 0x0c, 0x92, 0x41, 0x09, 0x0a, 0x07, 0xd2, 0x01, 0x04, 0x66, 0x61, 0x72,
	0x6d, 0x22, 0x10, 0x0a, 0x0e, 0x42, 0x75, 0x79, 0x42, 0x61, 0x72, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x42, 0x75, 0x79, 0x42, 0x61, 0x72, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5e, 0x0a, 0x11, 0x42, 0x75, 0x79, 0x46, 0x65, 0x65,
	0x64, 0x42, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x62,
	0x61, 0x72, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x61,
	0x72, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x3a, 0x18, 0x92, 0x41,
	0x15, 0x0a, 0x13, 0xd2, 0x01, 0x07, 0x62, 0x61, 0x72, 0x6e, 0x5f, 0x69, 0x64, 0xd2, 0x01, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x42, 0x75, 0x79, 0x46, 0x65, 0x65,
	0x64, 0x42, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3d, 0x0a, 0x11,
	0x42, 0x75, 0x79, 0x43, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x61, 0x72, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x62, 0x61, 0x72, 0x6e, 0x49, 0x64, 0x3a, 0x0f, 0x92, 0x41, 0x0c, 0x0a,
	0x0a, 0xd2, 0x01, 0x07, 0x62, 0x61, 0x72, 0x6e, 0x5f, 0x69, 0x64, 0x22, 0x24, 0x0a, 0x12, 0x42,
	0x75, 0x79, 0x43, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x47, 0x0a, 0x12, 0x53, 0x65, 0x6c, 0x6c, 0x43, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x69, 0x63, 0x6b,
	0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x69,
	0x63, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x3a, 0x12, 0x92, 0x41, 0x0f, 0x0a, 0x0d, 0xd2, 0x01, 0x0a,
	0x63, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x65,
	0x6c, 0x6c, 0x43, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x47, 0x0a, 0x12, 0x46, 0x65, 0x65, 0x64, 0x43, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x69, 0x63, 0x6b,
	0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x69,
	0x63, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x3a, 0x12, 0x92, 0x41, 0x0f, 0x0a, 0x0d, 0xd2, 0x01, 0x0a,
	0x63, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x46, 0x65,
	0x65, 0x64, 0x43, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x45, 0x0a, 0x19, 0x46, 0x65, 0x65, 0x64, 0x43, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e,
	0x73, 0x4f, 0x66, 0x42, 0x61, 0x72, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x62, 0x61, 0x72, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x62, 0x61, 0x72, 0x6e, 0x49, 0x64, 0x3a, 0x0f, 0x92, 0x41, 0x0c, 0x0a, 0x0a, 0xd2, 0x01,
	0x07, 0x62, 0x61, 0x72, 0x6e, 0x5f, 0x69, 0x64, 0x22, 0x1c, 0x0a, 0x1a, 0x46, 0x65, 0x65, 0x64,
	0x43, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x73, 0x4f, 0x66, 0x42, 0x61, 0x72, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xbd, 0x08, 0x0a, 0x0b, 0x46, 0x61, 0x72, 0x6d, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x52, 0x0a, 0x07, 0x4e, 0x65, 0x77, 0x46, 0x61, 0x72,
	0x6d, 0x12, 0x21, 0x2e, 0x63, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x5f, 0x66, 0x61, 0x72, 0x6d,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x77, 0x46, 0x61, 0x72, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x63, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x5f, 0x66,
	0x61, 0x72, 0x6d, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x77, 0x46, 0x61, 0x72, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5b, 0x0a, 0x0a, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x46, 0x61, 0x72, 0x6d, 0x12, 0x24, 0x2e, 0x63, 0x68, 0x69, 0x63, 0x6b,
	0x65, 0x6e, 0x5f, 0x66, 0x61, 0x72, 0x6d, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x46, 0x61, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25,
	0x2e, 0x63, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x5f, 0x66, 0x61, 0x72, 0x6d, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x61, 0x72, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x73, 0x0a, 0x12, 0x46, 0x65, 0x65, 0x64, 0x43,
	0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x73, 0x4f, 0x66, 0x42, 0x61, 0x72, 0x6e, 0x12, 0x2c, 0x2e,
	0x63, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x5f, 0x66, 0x61, 0x72, 0x6d, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x43, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x73, 0x4f, 0x66,
	0x42, 0x61, 0x72, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x63, 0x68,
	0x69, 0x63, 0x6b, 0x65, 0x6e, 0x5f, 0x66, 0x61, 0x72, 0x6d, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x46, 0x65, 0x65, 0x64, 0x43, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x73, 0x4f, 0x66, 0x42, 0x61,
	0x72, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6e, 0x0a, 0x0b,
	0x46, 0x61, 0x72, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x25, 0x2e, 0x63, 0x68,
	0x69, 0x63, 0x6b, 0x65, 0x6e, 0x5f, 0x66, 0x61, 0x72, 0x6d, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x46, 0x61, 0x72, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x26, 0x2e, 0x63, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x5f, 0x66, 0x61, 0x72,
	0x6d, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x61, 0x72, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x10, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x0a, 0x12, 0x08, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x61, 0x72, 0x6d, 0x12, 0x6f, 0x0a, 0x07,
	0x42, 0x75, 0x79, 0x42, 0x61, 0x72, 0x6e, 0x12, 0x21, 0x2e, 0x63, 0x68, 0x69, 0x63, 0x6b, 0x65,
	0x6e, 0x5f, 0x66, 0x61, 0x72, 0x6d, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x75, 0x79, 0x42,
	0x61, 0x72, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x63, 0x68, 0x69,
	0x63, 0x6b, 0x65, 0x6e, 0x5f, 0x66, 0x61, 0x72, 0x6d, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x42,
	0x75, 0x79, 0x42, 0x61, 0x72, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1d,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x3a, 0x01, 0x2a, 0x22, 0x12, 0x2f, 0x76, 0x31, 0x2f, 0x66,
	0x61, 0x72, 0x6d, 0x2f, 0x62, 0x61, 0x72, 0x6e, 0x73, 0x2f, 0x62, 0x75, 0x79, 0x12, 0x8b, 0x01,
	0x0a, 0x0a, 0x42, 0x75, 0x79, 0x46, 0x65, 0x65, 0x64, 0x42, 0x61, 0x67, 0x12, 0x24, 0x2e, 0x63,
	0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x5f, 0x66, 0x61, 0x72, 0x6d, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x42, 0x75, 0x79, 0x46, 0x65, 0x65, 0x64, 0x42, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x25, 0x2e, 0x63, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x5f, 0x66, 0x61, 0x72,
	0x6d, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x75, 0x79, 0x46, 0x65, 0x65, 0x64, 0x42, 0x61,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x30, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x2a, 0x3a, 0x01, 0x2a, 0x22, 0x25, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x61, 0x72, 0x6d, 0x2f, 0x62,
	0x61, 0x72, 0x6e, 0x73, 0x2f, 0x7b, 0x62, 0x61, 0x72, 0x6e, 0x5f, 0x69, 0x64, 0x7d, 0x2f, 0x62,
	0x75, 0x79, 0x2d, 0x66, 0x65, 0x65, 0x64, 0x2d, 0x62, 0x61, 0x67, 0x12, 0x7b, 0x0a, 0x0a, 0x42,
	0x75, 0x79, 0x43, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x12, 0x24, 0x2e, 0x63, 0x68, 0x69, 0x63,
	0x6b, 0x65, 0x6e, 0x5f, 0x66, 0x61, 0x72, 0x6d, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x75,
	0x79, 0x43, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x25, 0x2e, 0x63, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x5f, 0x66, 0x61, 0x72, 0x6d, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x42, 0x75, 0x79, 0x43, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x3a, 0x01,
	0x2a, 0x22, 0x15, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x61, 0x72, 0x6d, 0x2f, 0x63, 0x68, 0x69, 0x63,
	0x6b, 0x65, 0x6e, 0x73, 0x2f, 0x62, 0x75, 0x79, 0x12, 0x8c, 0x01, 0x0a, 0x0b, 0x53, 0x65, 0x6c,
	0x6c, 0x43, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x12, 0x25, 0x2e, 0x63, 0x68, 0x69, 0x63, 0x6b,
	0x65, 0x6e, 0x5f, 0x66, 0x61, 0x72, 0x6d, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6c,
	0x6c, 0x43, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x26, 0x2e, 0x63, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x5f, 0x66, 0x61, 0x72, 0x6d, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6c, 0x6c, 0x43, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x28, 0x3a,
	0x01, 0x2a, 0x22, 0x23, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x61, 0x72, 0x6d, 0x2f, 0x63, 0x68, 0x69,
	0x63, 0x6b, 0x65, 0x6e, 0x73, 0x2f, 0x7b, 0x63, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x5f, 0x69,
	0x64, 0x7d, 0x2f, 0x73, 0x65, 0x6c, 0x6c, 0x12, 0x8c, 0x01, 0x0a, 0x0b, 0x46, 0x65, 0x65, 0x64,
	0x43, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x12, 0x25, 0x2e, 0x63, 0x68, 0x69, 0x63, 0x6b, 0x65,
	0x6e, 0x5f, 0x66, 0x61, 0x72, 0x6d, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x65, 0x64,
	0x43, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26,
	0x2e, 0x63, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x5f, 0x66, 0x61, 0x72, 0x6d, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x43, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x28, 0x3a, 0x01,
	0x2a, 0x22, 0x23, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x61, 0x72, 0x6d, 0x2f, 0x63, 0x68, 0x69, 0x63,
	0x6b, 0x65, 0x6e, 0x73, 0x2f, 0x7b, 0x63, 0x68, 0x69, 0x63, 0x6b, 0x65, 0x6e, 0x5f, 0x69, 0x64,
	0x7d, 0x2f, 0x66, 0x65, 0x65, 0x64, 0x42, 0x13, 0x5a, 0x11, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_chicken_farmer_v1_farm_proto_rawDescOnce sync.Once
	file_chicken_farmer_v1_farm_proto_rawDescData = file_chicken_farmer_v1_farm_proto_rawDesc
)

func file_chicken_farmer_v1_farm_proto_rawDescGZIP() []byte {
	file_chicken_farmer_v1_farm_proto_rawDescOnce.Do(func() {
		file_chicken_farmer_v1_farm_proto_rawDescData = protoimpl.X.CompressGZIP(file_chicken_farmer_v1_farm_proto_rawDescData)
	})
	return file_chicken_farmer_v1_farm_proto_rawDescData
}

var file_chicken_farmer_v1_farm_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_chicken_farmer_v1_farm_proto_goTypes = []interface{}{
	(*Farm)(nil),                       // 0: chicken_farmer.v1.Farm
	(*Barn)(nil),                       // 1: chicken_farmer.v1.Barn
	(*Chicken)(nil),                    // 2: chicken_farmer.v1.Chicken
	(*NewFarmRequest)(nil),             // 3: chicken_farmer.v1.NewFarmRequest
	(*NewFarmResponse)(nil),            // 4: chicken_farmer.v1.NewFarmResponse
	(*DeleteFarmRequest)(nil),          // 5: chicken_farmer.v1.DeleteFarmRequest
	(*DeleteFarmResponse)(nil),         // 6: chicken_farmer.v1.DeleteFarmResponse
	(*FarmDetailsRequest)(nil),         // 7: chicken_farmer.v1.FarmDetailsRequest
	(*FarmDetailsResponse)(nil),        // 8: chicken_farmer.v1.FarmDetailsResponse
	(*BuyBarnRequest)(nil),             // 9: chicken_farmer.v1.BuyBarnRequest
	(*BuyBarnResponse)(nil),            // 10: chicken_farmer.v1.BuyBarnResponse
	(*BuyFeedBagRequest)(nil),          // 11: chicken_farmer.v1.BuyFeedBagRequest
	(*BuyFeedBagResponse)(nil),         // 12: chicken_farmer.v1.BuyFeedBagResponse
	(*BuyChickenRequest)(nil),          // 13: chicken_farmer.v1.BuyChickenRequest
	(*BuyChickenResponse)(nil),         // 14: chicken_farmer.v1.BuyChickenResponse
	(*SellChickenRequest)(nil),         // 15: chicken_farmer.v1.SellChickenRequest
	(*SellChickenResponse)(nil),        // 16: chicken_farmer.v1.SellChickenResponse
	(*FeedChickenRequest)(nil),         // 17: chicken_farmer.v1.FeedChickenRequest
	(*FeedChickenResponse)(nil),        // 18: chicken_farmer.v1.FeedChickenResponse
	(*FeedChickensOfBarnRequest)(nil),  // 19: chicken_farmer.v1.FeedChickensOfBarnRequest
	(*FeedChickensOfBarnResponse)(nil), // 20: chicken_farmer.v1.FeedChickensOfBarnResponse
}
var file_chicken_farmer_v1_farm_proto_depIdxs = []int32{
	1,  // 0: chicken_farmer.v1.Farm.barns:type_name -> chicken_farmer.v1.Barn
	2,  // 1: chicken_farmer.v1.Barn.chickens:type_name -> chicken_farmer.v1.Chicken
	0,  // 2: chicken_farmer.v1.FarmDetailsResponse.farm:type_name -> chicken_farmer.v1.Farm
	3,  // 3: chicken_farmer.v1.FarmService.NewFarm:input_type -> chicken_farmer.v1.NewFarmRequest
	5,  // 4: chicken_farmer.v1.FarmService.DeleteFarm:input_type -> chicken_farmer.v1.DeleteFarmRequest
	19, // 5: chicken_farmer.v1.FarmService.FeedChickensOfBarn:input_type -> chicken_farmer.v1.FeedChickensOfBarnRequest
	7,  // 6: chicken_farmer.v1.FarmService.FarmDetails:input_type -> chicken_farmer.v1.FarmDetailsRequest
	9,  // 7: chicken_farmer.v1.FarmService.BuyBarn:input_type -> chicken_farmer.v1.BuyBarnRequest
	11, // 8: chicken_farmer.v1.FarmService.BuyFeedBag:input_type -> chicken_farmer.v1.BuyFeedBagRequest
	13, // 9: chicken_farmer.v1.FarmService.BuyChicken:input_type -> chicken_farmer.v1.BuyChickenRequest
	15, // 10: chicken_farmer.v1.FarmService.SellChicken:input_type -> chicken_farmer.v1.SellChickenRequest
	17, // 11: chicken_farmer.v1.FarmService.FeedChicken:input_type -> chicken_farmer.v1.FeedChickenRequest
	4,  // 12: chicken_farmer.v1.FarmService.NewFarm:output_type -> chicken_farmer.v1.NewFarmResponse
	6,  // 13: chicken_farmer.v1.FarmService.DeleteFarm:output_type -> chicken_farmer.v1.DeleteFarmResponse
	20, // 14: chicken_farmer.v1.FarmService.FeedChickensOfBarn:output_type -> chicken_farmer.v1.FeedChickensOfBarnResponse
	8,  // 15: chicken_farmer.v1.FarmService.FarmDetails:output_type -> chicken_farmer.v1.FarmDetailsResponse
	10, // 16: chicken_farmer.v1.FarmService.BuyBarn:output_type -> chicken_farmer.v1.BuyBarnResponse
	12, // 17: chicken_farmer.v1.FarmService.BuyFeedBag:output_type -> chicken_farmer.v1.BuyFeedBagResponse
	14, // 18: chicken_farmer.v1.FarmService.BuyChicken:output_type -> chicken_farmer.v1.BuyChickenResponse
	16, // 19: chicken_farmer.v1.FarmService.SellChicken:output_type -> chicken_farmer.v1.SellChickenResponse
	18, // 20: chicken_farmer.v1.FarmService.FeedChicken:output_type -> chicken_farmer.v1.FeedChickenResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_chicken_farmer_v1_farm_proto_init() }
func file_chicken_farmer_v1_farm_proto_init() {
	if File_chicken_farmer_v1_farm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chicken_farmer_v1_farm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Farm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chicken_farmer_v1_farm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Barn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chicken_farmer_v1_farm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chicken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chicken_farmer_v1_farm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewFarmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chicken_farmer_v1_farm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewFarmResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chicken_farmer_v1_farm_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFarmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chicken_farmer_v1_farm_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFarmResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chicken_farmer_v1_farm_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FarmDetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chicken_farmer_v1_farm_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FarmDetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chicken_farmer_v1_farm_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyBarnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chicken_farmer_v1_farm_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyBarnResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chicken_farmer_v1_farm_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyFeedBagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chicken_farmer_v1_farm_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyFeedBagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chicken_farmer_v1_farm_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyChickenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chicken_farmer_v1_farm_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyChickenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chicken_farmer_v1_farm_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SellChickenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chicken_farmer_v1_farm_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SellChickenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chicken_farmer_v1_farm_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedChickenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chicken_farmer_v1_farm_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedChickenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chicken_farmer_v1_farm_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedChickensOfBarnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chicken_farmer_v1_farm_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedChickensOfBarnResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chicken_farmer_v1_farm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chicken_farmer_v1_farm_proto_goTypes,
		DependencyIndexes: file_chicken_farmer_v1_farm_proto_depIdxs,
		MessageInfos:      file_chicken_farmer_v1_farm_proto_msgTypes,
	}.Build()
	File_chicken_farmer_v1_farm_proto = out.File
	file_chicken_farmer_v1_farm_proto_rawDesc = nil
	file_chicken_farmer_v1_farm_proto_goTypes = nil
	file_chicken_farmer_v1_farm_proto_depIdxs = nil
}
