#!/bin/sh

# TODO move this to github actions

# Fail if any command fails.
set -e

## START BACKEND ##

# Make sure imports are consistently formatted.
#goimports -w=true .

# Run lint checks.
#golangci-lint run ./...

# All tests must pass.
go test ./...

cd ./api/proto
buf format -w
buf lint
cd ./../..

## END BACKEND ##
