// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"chicken-farmer/backend/internal/farmer"
	"chicken-farmer/backend/internal/farmer/mongo"
	grpc2 "chicken-farmer/backend/internal/pkg/grpc"
	"context"
	"go.uber.org/zap"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func initializeGRPCService(ctx context.Context, address string, logger *zap.SugaredLogger, farmGRPCConn grpc.ClientConnInterface) (*farmer.GRPCService, error) {
	datasource, err := mongo.ProvideDatasource(ctx)
	if err != nil {
		return nil, err
	}
	farmServiceClient := grpc2.NewFarmServiceClient(farmGRPCConn)
	farmGRPCClient := farmer.ProvideFarmGRPCClient(farmServiceClient)
	controller := farmer.ProvideController(logger, datasource, farmGRPCClient)
	grpcService := farmer.ProvideGRPCService(address, logger, controller)
	return grpcService, nil
}
