// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"chicken-farmer/backend/internal/farmer"
	"context"

	"go.uber.org/zap"

	_ "github.com/golang-migrate/migrate/v4/source/file"

	_ "github.com/lib/pq"
)

// Injectors from wire.go:

func initializeService(ctx context.Context, address string, logger *zap.SugaredLogger) (farmer.Service, error) {
	mongoDatabase, err := farmer.ProvideMongoDatabase(ctx)
	if err != nil {
		return farmer.Service{}, err
	}
	controller := farmer.ProvideController(mongoDatabase)
	service := farmer.ProvideService(address, logger, controller)
	return service, nil
}
