run:
  skip-dirs:
    - internal/chicken-old
linters:
  enable-all: true
  disable:
    - nosnakecase
    - interfacer
    - scopelint
    - deadcode
    - exhaustivestruct
    - exhaustruct
    - golint
    - gci
    - maligned
    - ifshort
    - structcheck
    - varcheck
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - wrapcheck
