// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.11
// source: api/proto/farm.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FarmServiceClient is the client API for FarmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FarmServiceClient interface {
	GetFarm(ctx context.Context, in *GetFarmRequest, opts ...grpc.CallOption) (*GetFarmResponse, error)
	BuyBarn(ctx context.Context, in *BuyBarnRequest, opts ...grpc.CallOption) (*BuyBarnResponse, error)
	BuyFeed(ctx context.Context, in *BuyFeedRequest, opts ...grpc.CallOption) (*BuyFeedResponse, error)
	BuyChicken(ctx context.Context, in *BuyChickenRequest, opts ...grpc.CallOption) (*BuyChickenResponse, error)
	FeedChicken(ctx context.Context, in *FeedChickenRequest, opts ...grpc.CallOption) (*FeedChickenResponse, error)
	FeedChickensOfBarn(ctx context.Context, in *FeedChickensOfBarnRequest, opts ...grpc.CallOption) (*FeedChickensOfBarnResponse, error)
}

type farmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFarmServiceClient(cc grpc.ClientConnInterface) FarmServiceClient {
	return &farmServiceClient{cc}
}

func (c *farmServiceClient) GetFarm(ctx context.Context, in *GetFarmRequest, opts ...grpc.CallOption) (*GetFarmResponse, error) {
	out := new(GetFarmResponse)
	err := c.cc.Invoke(ctx, "/grpc.FarmService/GetFarm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmServiceClient) BuyBarn(ctx context.Context, in *BuyBarnRequest, opts ...grpc.CallOption) (*BuyBarnResponse, error) {
	out := new(BuyBarnResponse)
	err := c.cc.Invoke(ctx, "/grpc.FarmService/BuyBarn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmServiceClient) BuyFeed(ctx context.Context, in *BuyFeedRequest, opts ...grpc.CallOption) (*BuyFeedResponse, error) {
	out := new(BuyFeedResponse)
	err := c.cc.Invoke(ctx, "/grpc.FarmService/BuyFeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmServiceClient) BuyChicken(ctx context.Context, in *BuyChickenRequest, opts ...grpc.CallOption) (*BuyChickenResponse, error) {
	out := new(BuyChickenResponse)
	err := c.cc.Invoke(ctx, "/grpc.FarmService/BuyChicken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmServiceClient) FeedChicken(ctx context.Context, in *FeedChickenRequest, opts ...grpc.CallOption) (*FeedChickenResponse, error) {
	out := new(FeedChickenResponse)
	err := c.cc.Invoke(ctx, "/grpc.FarmService/FeedChicken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmServiceClient) FeedChickensOfBarn(ctx context.Context, in *FeedChickensOfBarnRequest, opts ...grpc.CallOption) (*FeedChickensOfBarnResponse, error) {
	out := new(FeedChickensOfBarnResponse)
	err := c.cc.Invoke(ctx, "/grpc.FarmService/FeedChickensOfBarn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FarmServiceServer is the server API for FarmService service.
// All implementations must embed UnimplementedFarmServiceServer
// for forward compatibility
type FarmServiceServer interface {
	GetFarm(context.Context, *GetFarmRequest) (*GetFarmResponse, error)
	BuyBarn(context.Context, *BuyBarnRequest) (*BuyBarnResponse, error)
	BuyFeed(context.Context, *BuyFeedRequest) (*BuyFeedResponse, error)
	BuyChicken(context.Context, *BuyChickenRequest) (*BuyChickenResponse, error)
	FeedChicken(context.Context, *FeedChickenRequest) (*FeedChickenResponse, error)
	FeedChickensOfBarn(context.Context, *FeedChickensOfBarnRequest) (*FeedChickensOfBarnResponse, error)
	mustEmbedUnimplementedFarmServiceServer()
}

// UnimplementedFarmServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFarmServiceServer struct {
}

func (UnimplementedFarmServiceServer) GetFarm(context.Context, *GetFarmRequest) (*GetFarmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFarm not implemented")
}
func (UnimplementedFarmServiceServer) BuyBarn(context.Context, *BuyBarnRequest) (*BuyBarnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyBarn not implemented")
}
func (UnimplementedFarmServiceServer) BuyFeed(context.Context, *BuyFeedRequest) (*BuyFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyFeed not implemented")
}
func (UnimplementedFarmServiceServer) BuyChicken(context.Context, *BuyChickenRequest) (*BuyChickenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyChicken not implemented")
}
func (UnimplementedFarmServiceServer) FeedChicken(context.Context, *FeedChickenRequest) (*FeedChickenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FeedChicken not implemented")
}
func (UnimplementedFarmServiceServer) FeedChickensOfBarn(context.Context, *FeedChickensOfBarnRequest) (*FeedChickensOfBarnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FeedChickensOfBarn not implemented")
}
func (UnimplementedFarmServiceServer) mustEmbedUnimplementedFarmServiceServer() {}

// UnsafeFarmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FarmServiceServer will
// result in compilation errors.
type UnsafeFarmServiceServer interface {
	mustEmbedUnimplementedFarmServiceServer()
}

func RegisterFarmServiceServer(s grpc.ServiceRegistrar, srv FarmServiceServer) {
	s.RegisterService(&FarmService_ServiceDesc, srv)
}

func _FarmService_GetFarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).GetFarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.FarmService/GetFarm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).GetFarm(ctx, req.(*GetFarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FarmService_BuyBarn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyBarnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).BuyBarn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.FarmService/BuyBarn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).BuyBarn(ctx, req.(*BuyBarnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FarmService_BuyFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).BuyFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.FarmService/BuyFeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).BuyFeed(ctx, req.(*BuyFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FarmService_BuyChicken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyChickenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).BuyChicken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.FarmService/BuyChicken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).BuyChicken(ctx, req.(*BuyChickenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FarmService_FeedChicken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedChickenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).FeedChicken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.FarmService/FeedChicken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).FeedChicken(ctx, req.(*FeedChickenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FarmService_FeedChickensOfBarn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedChickensOfBarnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).FeedChickensOfBarn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.FarmService/FeedChickensOfBarn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).FeedChickensOfBarn(ctx, req.(*FeedChickensOfBarnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FarmService_ServiceDesc is the grpc.ServiceDesc for FarmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FarmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.FarmService",
	HandlerType: (*FarmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFarm",
			Handler:    _FarmService_GetFarm_Handler,
		},
		{
			MethodName: "BuyBarn",
			Handler:    _FarmService_BuyBarn_Handler,
		},
		{
			MethodName: "BuyFeed",
			Handler:    _FarmService_BuyFeed_Handler,
		},
		{
			MethodName: "BuyChicken",
			Handler:    _FarmService_BuyChicken_Handler,
		},
		{
			MethodName: "FeedChicken",
			Handler:    _FarmService_FeedChicken_Handler,
		},
		{
			MethodName: "FeedChickensOfBarn",
			Handler:    _FarmService_FeedChickensOfBarn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/farm.proto",
}
