---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-svc
  labels:
    app: time-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: time-svc
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: time-svc
    spec:
      containers:
        - name: time-svc
          image: ptiple/time-svc:latest
          resources:
            limits:
              cpu: "0.05"
              memory: 100Mi