// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"chicken-farmer/backend/internal/farm"
	grpc2 "chicken-farmer/backend/internal/pkg/grpc"
	"database/sql"

	"go.uber.org/zap"
	"google.golang.org/grpc"

	_ "github.com/golang-migrate/migrate/v4/source/file"

	_ "github.com/lib/pq"
)

// Injectors from wire.go:

func initializeService(address string, logger *zap.SugaredLogger, dbConnection *sql.DB, farmerGRPCConn grpc.ClientConnInterface) (farm.Service, error) {
	sqlDatabase, err := farm.ProvideSQLDatabase(dbConnection)
	if err != nil {
		return farm.Service{}, err
	}
	farmerServiceClient := grpc2.NewFarmerServiceClient(farmerGRPCConn)
	farmerService := farm.ProvideFarmerService(farmerServiceClient)
	controller := farm.ProvideController(sqlDatabase, farmerService)
	service := farm.ProvideService(address, logger, controller)
	return service, nil
}
