---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: 8080
      # Set fixed port so we don't have to keep changing where the code connects to
      nodePort: 31479
  selector:
    service: ambassador