---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: frontend-svc_mapping
      prefix: /app/
      service: frontend-svc:80
      labels:
        ambassador:
          - request_label:
            - http
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: web-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-svc
  labels:
    app: web-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-svc
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-svc
    spec:
      containers:
        - name: web-svc
          image: ptiple/proto-old-farmer-microservices-web:latest
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              cpu: 50m
              memory: 256Mi