---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    app: redis-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-svc
  labels:
    app: redis-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-svc
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis-svc
    spec:
      containers:
        - name: redis-svc
          image: redis:5.0.4
          command:
            - redis-server
            - --requirepass password
          env:
            - name: MASTER
              value: "true"
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: "0.1"
              memory: 100Mi
          volumeMounts:
            - mountPath: /redis-master-data
              name: data
      volumes:
        - name: data
          emptyDir: {}