---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: frontend-svc_mapping
      prefix: /app
      service: frontend-svc:8080
      labels:
        ambassador:
          - request_label:
            - http
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: frontend-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-svc
  labels:
    app: frontend-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-svc
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend-svc
    spec:
      containers:
        - name: frontend-svc
          image: ptiple/frontend-svc:latest
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: "0.1"
              memory: 100Mi