---
apiVersion: v1
kind: Service
metadata:
  name: barn-svc
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: barn-svc_mapping
      prefix: /barns/
      service: barn-svc:8080
      labels:
        ambassador:
          - request_label:
            - http
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: barn-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: barn-svc
  labels:
    app: barn-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barn-svc
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: barn-svc
    spec:
      containers:
        - name: barn-svc
          image: ptiple/barn-svc:latest
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: "0.1"
              memory: 100Mi
---
# MongoDB
apiVersion: v1
kind: Service
metadata:
  name: barn-svc-mongodb
spec:
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  selector:
    app: barn-svc-mongodb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: barn-svc-mongodata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: barn-svc-mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: barn-svc-mongodb
    spec:
      containers:
        - image: mongo
          name: barn-svc-mongodb
          ports:
            - containerPort: 27017
          env:
            # TODO get these from a kubernetes secret
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: barn-svc-mongodata
      restartPolicy: Always
      volumes:
        - name: barn-svc-mongodata
          persistentVolumeClaim:
            claimName: barn-svc-mongodata-pvc