---
apiVersion: v1
kind: Service
metadata:
  name: barnsvc
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: barnsvc_mapping
      prefix: /barns/
      service: barnsvc:8080
      labels:
        ambassador:
          - request_label:
            - http
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: barnsvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: barnsvc
  labels:
    app: barnsvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barnsvc
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: barnsvc
    spec:
      containers:
        - name: barnsvc
          image: ptiple/barnsvc:latest
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: "0.1"
              memory: 100Mi
---
# MongoDB
apiVersion: v1
kind: Service
metadata:
  name: barnsvc-mongodb
spec:
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  selector:
    app: barnsvc-mongodb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: barnsvc-mongodata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: barnsvc-mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: barnsvc-mongodb
    spec:
      containers:
        - image: mongo
          name: barnsvc-mongodb
          ports:
            - containerPort: 27017
          env:
            # TODO get these from a kubernetes secret
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: barnsvc-mongodata
      restartPolicy: Always
      volumes:
        - name: barnsvc-mongodata
          persistentVolumeClaim:
            claimName: barnsvc-mongodata-pvc