---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timesvc
  labels:
    app: timesvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timesvc
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: timesvc
    spec:
      containers:
        - name: timesvc
          image: ptiple/timesvc:latest
          resources:
            limits:
              cpu: "0.05"
              memory: 100Mi