// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"chicken-farmer/backend/internal/universe"
	"context"
	"github.com/ThreeDotsLabs/watermill/message"
	"go.uber.org/zap"
	"time"
)

// Injectors from wire.go:

func initializeTimeService(ctx context.Context, logger *zap.SugaredLogger, frequency time.Duration, publisher message.Publisher) (*universe.TimeService, error) {
	datasource, err := universe.ProvideMemoryDatasource()
	if err != nil {
		return nil, err
	}
	controller := universe.ProvideController(datasource, publisher)
	timeService := universe.ProvideTimeService(logger, controller, frequency)
	return timeService, nil
}
